name: Stips Notifications Checker

on:
  schedule:
    - cron: '* * * * *' # Runs every minute
  workflow_dispatch: # Optional: manual trigger

jobs:
  check_stips:
    runs-on: ubuntu-latest

    steps:
      - name: Check for new messages
        run: |
          # Make API request with your cookies
          response=$(curl -s 'https://stips.co.il/api?name=messages.count&api_params=%7B%7D' \
            -H 'Cookie: _ga=GA1.3.547378152.1726079580; __gsas=ID=1ebb46c307983df9:T=1727190456:RT=1727190456:S=ALNI_MagehX6oaoLZg97y7ikR-c9mGR5Hw; Login%5FUser=hashedpassword=EDHJFsGEEKrrpsFHqKprDIoGDIsLIprs&mail=zn6n0Bnu%2ExL%40tznvy%2Ep1z&rememberme=true&stype=75r4&id=GHEFLG&password=; _gid=GA1.3.1310715032.1730917325; ASPSESSIONIDCERASRCS=KMLNGBEBJPEDBECPHEGEBDAJ; _gat=1; ASPSESSIONIDAETDSRAS=EPFFHLACJMDIICIFJNCHFGKM; _ga_LYRZGGS0YG=GS1.3.1730981977.69.0.1730981977.0.0.0')

          # Extract counts
          messages_count=$(echo "$response" | jq '.data.messagesCount')
          notifications_count=$(echo "$response" | jq '.data.notificationsCount')

          echo "Messages: $messages_count, Notifications: $notifications_count"

          # Check if we need to send a notification
          if [ "$messages_count" -ne 0 ] || [ "$notifications_count" -ne 0 ]; then
            message="🔥 Hey cutie! You have $messages_count new messages and $notifications_count new notifications waiting for you on Stips! 💌✨"

            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
              -d text="$message"
          else
            echo "No new messages or notifications 💭"
          fi
